tasks:
 - tox -e py27-flake8
 - tox -e py35-flake8
 - tox -e py27-isort
 - tox -e py35-isort
 - tox -e py27-django-18
 - tox -e py27-django-19
 - tox -e py35-django-18
 - tox -e py35-django-19
 - tox -e coverage

verbose_tasks:
  - tox -e coverage

coverage:
  path: coverage.xml
  parser: python
