tasks:
 - tox -e py27-flake8
 - tox -e py34-flake8
 - tox -e py27-isort
 - tox -e py34-isort
 - tox -e py27-django-14
 - tox -e py27-django-15
 - tox -e py27-django-16
 - tox -e py27-django-17
 - tox -e py27-django-18
 - tox -e py34-django-15
 - tox -e py34-django-16
 - tox -e py34-django-17
 - tox -e py34-django-18
 - coverage combine && coverage xml
 - coverage report

coverage:
  path: coverage.xml
  parser: python
